spring:
  config:
    activate:
      on-profile: qa
  
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:hmspro
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2Console
