spring:
  application:
    name: doctor-service
  cloud:
    config:
      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: beans,mappings,metrics,env,loggers,shutdown,medilab-actuator,refresh
  endpoint:
    shutdown:
      enabled: true 
doctor:
  fee: 300
server:
  port: 6062

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-doctor-service
    username: root
    password: root
  jpa:
    properties:
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect 
          format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 6062
---
spring:
  profiles: qa
  
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:hmspro
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2Console
server:
  port: 6063
---
spring:
  profiles:
    active: qa
     