spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-doctor-service
    username: root
    password: root
  jpa:
    properties:
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect 
          format_sql: true
    hibernate:
      ddl-auto: update