spring:
  application:
    name: doctor-service
  profiles:
    active: dev
server:
  port: 6062

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings,metrics,env,loggers,shutdown,medilab-actuator
  endpoint:
    shutdown:
      enabled: true
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://medilab-department-service-mysql:3306/medilab-department-service
    url: jdbc:mysql://localhost:3306/medilab-doctor-service
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
  config:
    activate:
      on-profile: dev
---
spring:
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:hmspro
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2Console
  config:
    activate:
      on-profile: qa
