spring:
  application:
    name: medilab-doctor-service
  h2:
    console:
      enabled: true
      path: /h2Console
server:
  port: 5002

medilab:
 doctorFee: 400
   
logging:
  file: 
    name: doctor.log
    
