spring:
  application:
    name: medilab-department-service
  h2:
    console:
      enabled: true
      path: /h2Console

logging:
  file: 
    name: department.log
springdoc:
  swagger-ui:
    path: /department-swagger.html
  api-docs:
    enabled: true
    path: /department-api-doc.html

 


    
