spring:
  application:
    name: vehicle-management-service
  jpa:
    show-sql: true
    generate-ddl: true

  cloud:
    config:
      uri:
      - http://localhost:8888/
      profile: stage
server:
  port: 9191

springdoc:
  swagger-ui:
    path: /vehicle-service.html
  api-docs:
    enabled: true
    path: /vehicle-service.doc

info:
 application: 
  name: vehicle management system
  version: 1.0
 databse: mysql5.46

management: 
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
todays: 
 vehicle:
   fare: 30
   per:
    km: 1
---
spring:
  #profiles: dev
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vehicle-management-service
    #url: jdbc:mysql://vehicle-service-mysql:3306/vehicle-service
    driver-class-name: com.mysql.cj.jdbc.Driver
  #cloud:
    #config:
      #profile: dev

---
spring:
  #profiles: stage
  config:
    activate:
      on-profile: stage
  h2:
    console:
      enabled: true
      path: /h2Console
  #cloud:
    #config:
      #profile: stage
